### ISSUE TITLE
Paths config missing in Play setup JS

### ISSUE THREAD

**Issue by jirihelmich** [webjars/nvd3#4]
Hi,

it seems that this webjar does not export paths configuration into the output of

```
@Html(org.webjars.RequireJS.getSetupJavaScript(routes.WebJarAssets.at("").url))
```

```
requirejs.config({"paths": ... });
```

is completely missing.

**Comment by jamesward** [comment]
Make sure you are using the latest version `1.1.15-beta-2`. It should have the needed RequireJS config.

**Comment by jirihelmich** [comment]
Oh, I see. I used the default one from webjars website. Thanks!

**Comment by jamesward** [comment]
Unfortunately it is hard to sort different version schemes correctly.  Sorry for the hassle.

**Comment by jirihelmich** [comment]
I understand. Moreover, there are some problems with nvd3 and its ecosystem, it seems that those repositories are no longer maintained. Maybe, it would be good idea to somehow indicate that a webjar is based on a rather older commit. :-)
